services:
  nginx:
    image: nginx:stable-alpine3.19-perl
    ports:
      - "3000:80"
    volumes:
      - ./app:/var/www/app
      - ./api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysqldb

  php:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html

  mysqldb:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foodventeny_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysqldb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3001:80"
    depends_on:
      - mysqldb